---
title: "part 2 R-project"
author: "Ameeta"
date: "2025-09-24"
output: html_document
---
Part2: Examining biological sequence diversity
Download the whole set of coding DNA sequences for E. coli and your organism of interest. How many coding sequences are present in these organisms? Present this in the form of a table. Describe any differences between the two organisms. 
```{r loading package}
suppressPackageStartupMessages({
  library("seqinr") # is a package designed to process and analyse sequence data.
  library("R.utils") # general utilities like zip and unzip
})
# loading e.coli and Saprospirales data 
library("R.utils")

URL="https://ftp.ensemblgenomes.ebi.ac.uk/pub/bacteria/release-62/fasta/bacteria_58_collection/saprospirales_bacterium_gca_003448025/cds/Saprospirales_bacterium_gca_003448025.ASM344802v1.cds.all.fa.gz"
download.file(URL,destfile="saprospirales_cds.fa.gz")
URL="http://ftp.ensemblgenomes.org/pub/bacteria/release-53/fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655_gca_000005845/cds/Escherichia_coli_str_k_12_substr_mg1655_gca_000005845.ASM584v2.cds.all.fa.gz"
download.file(URL,destfile="ecoli_cds.fa.gz")

gunzip("saprospirales_cds.fa.gz")
gunzip("ecoli_cds.fa.gz")

list.files()
# Reading the FASTA file 
library("seqinr")
e.coli_cds <- seqinr::read.fasta("ecoli_cds.fa")
saprospirales_cds <- seqinr::read.fasta("saprospirales_cds.fa")
# count number of sequences 
e.coli_number <- length(e.coli_cds)
sapropirales_num <- length(saprospirales_cds)
# create table 
cds_table <- data.frame(
  Bacteria = c("E.coli", "Saprospirales"),
  CDS_count = c(e.coli_number, sapropirales_num)
)
cds_table
```

## loading e.coli and saprospirales data 
```{r downloading e.coli and saprospirales genome}
```
```{r loading seqinr library}
library("seqinr")
```
## reading the fasta file
```{r}
e.coli_cds <- seqinr::read.fasta("ecoli_cds.fa")
saprospirales_cds <- seqinr::read.fasta("saprospirales_cds.fa")
# count number of sequences 
e.coli_number <- length(e.coli_cds)
sapropirales_num <- length(saprospirales_cds)
# create table 
cds_table <- data.frame(
  Bacteria = c("E.coli", "Saprospirales"),
  CDS_count = c(e.coli_number, sapropirales_num)
)
cds_table
```
```{r}
summary(cds)
```

